import type { Metadata } from 'next';
import { Poppins, Bricolage_Grotesque, Bagel_Fat_One } from 'next/font/google';
import { ThemeProvider } from '@/providers/theme-provider';
import { SessionProvider } from 'next-auth/react';

import './globals.css';
import { ToastContainer } from 'react-toastify';
import Footer from '@/components/common/footer';

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  weight: 'variable',
  variable: '--font-bricolage',
});

const bagelFatOne = Bagel_Fat_One({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-bagel-fat-one',
});

const poppins = Poppins({
  variable: '--font-Poppins',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600'],
});

export const metadata: Metadata = {
  title: 'Saphala',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} ${bricolage.variable} ${bagelFatOne.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider refetchInterval={60}>
            {children}
            <Footer />
          </SessionProvider>
        </ThemeProvider>
        <ToastContainer position="top-center" theme="colored" />
      </body>
    </html>
  );
}
