import type { Metadata } from 'next';
import { ThemeProvider } from '@/providers/theme-provider';
import { SessionProvider } from 'next-auth/react';

import './globals.css';
import { ToastContainer } from 'react-toastify';
import Footer from '@/components/common/footer';
import { poppins } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Saphala',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider refetchInterval={60}>
            {children}
            <Footer />
          </SessionProvider>
        </ThemeProvider>
        <ToastContainer position="top-center" theme="colored" />
      </body>
    </html>
  );
}
